"""
Copy the existing Cosmos predictions (already generated by pipeline.py).
"""
import json
from pathlib import Path

SRC = Path("../robot-task-monitoring/outputs/predictions.jsonl")
DST = Path("predictions_cosmos.jsonl")

if SRC.exists():
    lines = SRC.read_text().strip().split("\n")
    DST.write_text("\n".join(lines) + "\n")
    print(f"✓ Copied {len(lines)} Cosmos predictions to {DST}")
else:
    print(f"✗ {SRC} not found. Run pipeline.py first.")
